### ISSUE TITLE
Feature Request: Add mode / band

### ISSUE THREAD

**Issue by Bastiti** [DB4SCW/coordinatorr#2]
Hello,

Regulation in some countries says that you can have a station per mode/band.

I have a suggestion. When pushing for activate callsign or planning activation:
- allow user to choose mode (CW/SSB/DIGITAL).
- allow user to choose band.

Thanks for reading this feature Request.

73,
ON4BCY

**Comment by DB4SCW** [comment]
Hey there, 

thanks for the feature request. That would change the whole matching logic, so that's not a short 3 lines of code.

Just to be sure what your regulation allows and that I understand correctly - would this "snapshot of activity" be legal?
Operator 1: 20m CW
Operator 2: 20m FT8
Operator 3: 20m SSB
Operator 4: 40m SSB
All at the same time, using the same callsign?

If not, please specify which activity is allowed to happen at once according to law.

Thank you!

73 de Stefan, DB4SCW

**Comment by Bastiti** [comment]
Your example works for french laws.

**Comment by DB4SCW** [comment]
Ok. In the pull request I implemented both that scenario as well as "1 operator per band" which (to my knowledge) is law in Switzerland.

At the moment I'm testing this feature because this excessivly impacted the core implementation of coordinatorr. If it holds up to the tests, it will be available in the upcoming V1.0.0 release.

If you like, you can help by pulling the PR youself and test, too.

**Comment by DB4SCW** [comment]
PR is merged into dev after tests. It will remain in dev and get further tests until release of V1.0.0
